# Generated by Django 5.2.2 on 2025-06-10 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('max_daily_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Daily Capacity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('categories_handled', models.ManyToManyField(blank=True, to='inventory.category', verbose_name='Categories Handled')),
            ],
            options={
                'verbose_name': 'Workstation',
                'verbose_name_plural': 'Workstations',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Equipment Name')),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='workstation.workstation')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='WorkstationRawMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.PositiveIntegerField(verbose_name='Quantity Consumed')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pc', 'Piece'), ('m', 'Meter'), ('g', 'Gram'), ('ml', 'Milliliter'), ('box', 'Box'), ('packet', 'Packet'), ('bottle', 'Bottle'), ('other', 'Other')], default='pc', max_length=20, verbose_name='Unit')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='inventory.rawmaterial', verbose_name='Raw Material')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstation_delivered_raw_materials', to='accounts.transporteruser', verbose_name='Transporter')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstation_raw_materials', to='accounts.workeruser', verbose_name='Worker')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='workstation.workstation', verbose_name='Workstation')),
            ],
            options={
                'verbose_name': 'Raw Material Consumption',
                'verbose_name_plural': 'Raw Materials Consumption',
            },
        ),
        migrations.CreateModel(
            name='WorkstationPreparedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pc', 'Piece'), ('m', 'Meter'), ('g', 'Gram'), ('ml', 'Milliliter'), ('box', 'Box'), ('packet', 'Packet'), ('bottle', 'Bottle'), ('other', 'Other')], default='pc', max_length=20, verbose_name='Unit')),
                ('preparation_date', models.DateField(blank=True, null=True, verbose_name='Preparation Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_products', to='inventory.rawmaterial', verbose_name='Raw Material')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_products', to='workstation.workstation', verbose_name='Workstation')),
            ],
            options={
                'verbose_name': 'Workstation Prepared Material',
                'verbose_name_plural': 'Workstation Prepared Materials',
                'unique_together': {('workstation', 'raw_material')},
            },
        ),
    ]
