# Generated by Django 5.2.2 on 2025-06-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
