# Generated by Django 5.2.2 on 2025-06-12 19:59

import accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0007_alter_packagedmaterial_options_and_more'),
        ('workstation', '0002_workstation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=accounts.fields.PrefixedIDField(editable=False, max_length=56, primary_key=True, serialize=False, unique=True, verbose_name='Equipment ID'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='id',
            field=accounts.fields.PrefixedIDField(editable=False, max_length=53, primary_key=True, serialize=False, unique=True, verbose_name='Workstation ID'),
        ),
        migrations.AlterField(
            model_name='workstationpreparedmaterial',
            name='id',
            field=accounts.fields.PrefixedIDField(editable=False, max_length=56, primary_key=True, serialize=False, unique=True, verbose_name='Prepared Material ID'),
        ),
        migrations.AlterField(
            model_name='workstationrawmaterialconsumption',
            name='id',
            field=accounts.fields.PrefixedIDField(editable=False, max_length=56, primary_key=True, serialize=False, unique=True, verbose_name='Consumption ID'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['id'], name='eq_id_index'),
        ),
        migrations.AddIndex(
            model_name='workstation',
            index=models.Index(fields=['id'], name='ws_id_index'),
        ),
        migrations.AddIndex(
            model_name='workstationpreparedmaterial',
            index=models.Index(fields=['id'], name='ws_prepared_mat_id_index'),
        ),
        migrations.AddIndex(
            model_name='workstationrawmaterialconsumption',
            index=models.Index(fields=['id'], name='ws_rm_id_index'),
        ),
    ]
