# Generated by Django 5.2.2 on 2025-06-12 21:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0003_alter_equipment_id_alter_workstation_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workstationpreparedmaterial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workstationpreparedmaterial',
            name='workstation_raw_material_consumption',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workstation.workstationrawmaterialconsumption', verbose_name='Workstation Raw Material Consumption'),
        ),
        migrations.AlterField(
            model_name='workstationpreparedmaterial',
            name='preparation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Preparation Date'),
        ),
        migrations.AlterField(
            model_name='workstationrawmaterialconsumption',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='workstationrawmaterialconsumption',
            name='quantity_consumed',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity Consumed'),
        ),
        migrations.RemoveField(
            model_name='workstationpreparedmaterial',
            name='raw_material',
        ),
        migrations.RemoveField(
            model_name='workstationpreparedmaterial',
            name='workstation',
        ),
    ]
