# Generated by Django 5.2.2 on 2025-06-12 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0004_alter_workstationpreparedmaterial_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstationpreparedmaterial',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
    ]
