# Generated by Django 5.2.2 on 2025-06-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_marketuser_alter_user_role'),
        ('workstation', '0002_workstation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_distributed', models.PositiveIntegerField(verbose_name='Quantity Distributed')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pc', 'Piece'), ('m', 'Meter'), ('g', 'Gram'), ('ml', 'Milliliter'), ('box', 'Box'), ('packet', 'Packet'), ('bottle', 'Bottle'), ('other', 'Other')], default='pc', max_length=20, verbose_name='Unit')),
                ('distribution_date', models.DateField(auto_now_add=True, verbose_name='Distribution Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_distributions', to='accounts.marketuser', verbose_name='Market')),
                ('prepared_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='workstation.workstationpreparedmaterial', verbose_name='Prepared Material')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_distributions', to='accounts.transporteruser', verbose_name='Transporter')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='workstation.workstation', verbose_name='Workstation')),
            ],
            options={
                'verbose_name': 'Distribution',
                'verbose_name_plural': 'Distributions',
            },
        ),
    ]
