# Generated by Django 5.2.2 on 2025-06-12 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
        ('inventory', '0005_rename_stored_location_packagedmaterial_storage_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={},
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='prepared_material',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='workstation',
        ),
        migrations.AddField(
            model_name='distribution',
            name='packaged_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='inventory.packagedmaterial'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distribution_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='market',
            field=models.ForeignKey(limit_choices_to={'role': 'market'}, on_delete=django.db.models.deletion.CASCADE, related_name='market_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='quantity_distributed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='transporter',
            field=models.ForeignKey(limit_choices_to={'role': 'transporter'}, on_delete=django.db.models.deletion.CASCADE, related_name='transporter_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pc', 'Piece'), ('m', 'Meter'), ('g', 'Gram'), ('ml', 'Milliliter'), ('box', 'Box'), ('packet', 'Packet'), ('bottle', 'Bottle'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
