# Generated by Django 5.2.2 on 2025-06-12 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_alter_distribution_packaged_material'),
        ('inventory', '0005_rename_stored_location_packagedmaterial_storage_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='packaged_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='inventory.packagedmaterial'),
        ),
    ]
