# Generated by Django 5.2.2 on 2025-06-13 11:18

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.managers.CustomerUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Admin'), (1, 'Inventory Coordinator'), (2, 'Worker'), (3, 'Transporter'), (4, 'Customer'), (5, 'Other')], verbose_name='Role'),
        ),
    ]
