# Generated by Django 5.2.2 on 2025-06-10 18:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('requires_temperature_control', models.BooleanField(default=False, verbose_name='Requires Temperature Control')),
                ('max_processing_time_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Processing Time (Hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Supplier Name')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Contact Information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='PackagedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pc', 'Piece'), ('m', 'Meter'), ('g', 'Gram'), ('ml', 'Milliliter'), ('box', 'Box'), ('packet', 'Packet'), ('bottle', 'Bottle'), ('other', 'Other')], default='pc', max_length=20, verbose_name='Unit')),
                ('package_date', models.DateField(blank=True, null=True, verbose_name='Package Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed_materials', to='accounts.workeruser', verbose_name='Worker')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, null=True, verbose_name='Material Name')),
                ('initial_quantity', models.PositiveIntegerField(default=0, verbose_name='Initial Quantity')),
                ('current_quantity', models.PositiveIntegerField(default=0, verbose_name='Current Quantity')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pc', 'Piece'), ('m', 'Meter'), ('g', 'Gram'), ('ml', 'Milliliter'), ('box', 'Box'), ('packet', 'Packet'), ('bottle', 'Bottle'), ('other', 'Other')], default='pc', max_length=20, verbose_name='Unit')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Production Date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('quality_score', models.PositiveIntegerField(default=0, help_text='Quality score from 0 to 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Quality Score')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=20, verbose_name='Status')),
                ('received_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Received Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('storage_location', models.CharField(max_length=100, null=True, verbose_name='Storage Location')),
                ('storage_temperature', models.PositiveIntegerField(blank=True, null=True, verbose_name='Storage Temperature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='inventory.category', verbose_name='Category')),
                ('inventory_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='accounts.inventorycoordinatoruser', verbose_name='Inventory Coordinator')),
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': 'Raw Materials',
            },
        ),
        migrations.CreateModel(
            name='ReadyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_check', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Quality Check')),
                ('stored_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stored Location')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pc', 'Piece'), ('m', 'Meter'), ('g', 'Gram'), ('ml', 'Milliliter'), ('box', 'Box'), ('packet', 'Packet'), ('bottle', 'Bottle'), ('other', 'Other')], default='pc', max_length=20, verbose_name='Unit')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('inventory_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_materials', to='accounts.inventorycoordinatoruser', verbose_name='Inventory Coordinator')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_ready_materials', to='accounts.transporteruser', verbose_name='Transporter')),
            ],
        ),
    ]
