# Generated by Django 5.2.2 on 2025-06-08 20:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Distributor Name')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Contact Information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Raw Material Name')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pc', 'Piece'), ('m', 'Meter'), ('g', 'Gram'), ('ml', 'Milliliter'), ('box', 'Box'), ('packet', 'Packet'), ('bottle', 'Bottle'), ('other', 'Other')], default='pc', max_length=20, verbose_name='Unit')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('quality_check', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Quality Check')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=20, verbose_name='Status')),
                ('stored_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stored Location')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='inventory.category', verbose_name='Category')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='inventory.distributor', verbose_name='Distributor')),
                ('inventory_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='accounts.inventorycoordinatoruser', verbose_name='Inventory Coordinator')),
            ],
        ),
    ]
