# Generated by Django 5.2.2 on 2025-06-10 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('workstation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readymaterial',
            name='workstation_raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_materials', to='workstation.workstationpreparedmaterial', verbose_name='Raw Material'),
        ),
        migrations.AddField(
            model_name='packagedmaterial',
            name='ready_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed_materials', to='inventory.readymaterial', verbose_name='Ready Material'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='inventory.supplier', verbose_name='Supplier'),
        ),
    ]
