# Generated by Django 5.2.2 on 2025-06-10 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readymaterial',
            name='quality_check',
        ),
        migrations.AddField(
            model_name='packagedmaterial',
            name='packaging_type',
            field=models.CharField(choices=[('box', 'Box'), ('packet', 'Packet'), ('bottle', 'Bottle'), ('other', 'Other')], default='box', max_length=20, verbose_name='Packaging Type'),
        ),
        migrations.AddField(
            model_name='packagedmaterial',
            name='stored_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stored Location'),
        ),
        migrations.AddField(
            model_name='packagedmaterial',
            name='stored_temperature',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stored Temperature'),
        ),
        migrations.AddField(
            model_name='readymaterial',
            name='quality_score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Quality Score'),
        ),
        migrations.AddField(
            model_name='readymaterial',
            name='stored_temperature',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stored Temperature'),
        ),
    ]
