# Generated by Django 5.2.2 on 2025-06-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_readymaterial_quality_check_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagedmaterial',
            old_name='packaging_type',
            new_name='package_type',
        ),
    ]
