# Generated by Django 5.2.2 on 2025-06-12 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_stored_location_packagedmaterial_storage_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='received_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Received Date'),
        ),
    ]
