# Generated by Django 5.2.2 on 2025-06-12 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_readymaterial_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedmaterial',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='packagedmaterial',
            name='package_quantity',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Package Quantity'),
        ),
        migrations.AddField(
            model_name='packagedmaterial',
            name='package_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pc', 'Piece'), ('m', 'Meter'), ('g', 'Gram'), ('ml', 'Milliliter'), ('box', 'Box'), ('packet', 'Packet'), ('bottle', 'Bottle'), ('other', 'Other')], default='pc', max_length=20, verbose_name='Package Unit'),
        ),
        migrations.AddField(
            model_name='packagedmaterial',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Production Date'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='current_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Current Quantity'),
        ),
        migrations.AlterField(
            model_name='readymaterial',
            name='current_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Current Quantity'),
        ),
    ]
