# Generated by Django 5.2.2 on 2025-06-12 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_packagedmaterial_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedmaterial',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='initial_quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Initial Quantity'),
        ),
        migrations.AlterField(
            model_name='readymaterial',
            name='initial_quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Initial Quantity'),
        ),
    ]
