# Generated by Django 5.2.2 on 2025-06-13 11:32

import accounts.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_packagedmaterial_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='material_name',
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', accounts.fields.PrefixedIDField(editable=False, max_length=52, primary_key=True, serialize=False, unique=True, verbose_name='Raw Material ID')),
                ('material_name', models.CharField(max_length=100, null=True, verbose_name='Material Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='inventory.category', verbose_name='Category')),
                ('suppliers', models.ManyToManyField(related_name='materials', to='inventory.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='inventory.material', verbose_name='Material'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['id'], name='material_id_index'),
        ),
    ]
