# Generated by Django 5.2.2 on 2025-06-13 16:17

import accounts.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_customeruser_alter_user_role'),
        ('inventory', '0012_material_created_at_material_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', accounts.fields.PrefixedIDField(editable=False, max_length=56, primary_key=True, serialize=False, unique=True, verbose_name='Product ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'indexes': [models.Index(fields=['id'], name='pcat_id_index')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', accounts.fields.PrefixedIDField(editable=False, max_length=55, primary_key=True, serialize=False, unique=True, verbose_name='Product ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.productcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', accounts.fields.PrefixedIDField(editable=False, max_length=54, primary_key=True, serialize=False, unique=True, verbose_name='Product ID')),
                ('quantity_consumed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quality Consumed')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material', verbose_name='Material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='restaurant.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'verbose_name_plural': 'Recipe Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', accounts.fields.PrefixedIDField(editable=False, max_length=53, primary_key=True, serialize=False, unique=True, verbose_name='Restaurant ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurant',
                'indexes': [models.Index(fields=['id'], name='rs_id_index')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantPackagedMaterial',
            fields=[
                ('id', accounts.fields.PrefixedIDField(editable=False, max_length=54, primary_key=True, serialize=False, unique=True, verbose_name='Restaurant Package Material ID')),
                ('initial_package_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Initial Package Quantity')),
                ('current_package_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Current Package Quantity')),
                ('unit', models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pc', 'Piece'), ('m', 'Meter'), ('g', 'Gram'), ('ml', 'Milliliter'), ('box', 'Box'), ('packet', 'Packet'), ('bottle', 'Bottle'), ('other', 'Other')], max_length=20, null=True, verbose_name='Unit')),
                ('delivery_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Delivery Date')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Production Date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('storage_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stored Location')),
                ('storage_temperature', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stored Temperature')),
                ('finished_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_delivered_ready_materials', to='accounts.transporteruser', verbose_name='Transporter')),
            ],
            options={
                'verbose_name': 'Restaurant Packaged Material',
                'verbose_name_plural': 'Restaurant Packaged Materials',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id'], name='prod_id_index'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['id'], name='ing_id_index'),
        ),
        migrations.AddIndex(
            model_name='restaurantpackagedmaterial',
            index=models.Index(fields=['id'], name='rpm_id_index'),
        ),
    ]
