# Generated by Django 5.2.2 on 2025-06-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_material_created_at_material_updated_at'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantpackagedmaterial',
            name='package_material',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.packagedmaterial', verbose_name='Package Material'),
        ),
        migrations.AddField(
            model_name='restaurantpackagedmaterial',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_package_materials', to='restaurant.restaurant', verbose_name='Restaurant'),
        ),
    ]
