# Generated by Django 5.2.2 on 2025-06-14 07:54

import accounts.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_material_created_at_material_updated_at'),
        ('orders', '0002_order_restaurant'),
        ('restaurant', '0002_restaurantpackagedmaterial_package_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantpackagedmaterial',
            name='material',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.material', verbose_name='Material'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RestaurantPackagedMaterialConsumption',
            fields=[
                ('id', accounts.fields.PrefixedIDField(editable=False, max_length=55, primary_key=True, serialize=False, unique=True, verbose_name='Consumption ID')),
                ('quantity_consumed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity Consumed')),
                ('consumption_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Consumption Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material', verbose_name='Material')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='orders.orderitem', verbose_name='Order Item')),
                ('restaurant_package_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantpackagedmaterial', verbose_name='Restaurant Package Material')),
            ],
            options={
                'verbose_name': 'Material Consumption',
                'verbose_name_plural': 'Material Consumptions',
                'indexes': [models.Index(fields=['id'], name='cons_id_index')],
            },
        ),
    ]
