# Generated by Django 5.2.2 on 2025-06-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurantpackagedmaterial_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpackagedmaterial',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
    ]
