# Generated by Django 5.2.2 on 2025-06-13 19:07

import accounts.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_customeruser_alter_user_role'),
        ('restaurant', '0002_restaurantpackagedmaterial_package_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', accounts.fields.PrefixedIDField(editable=False, max_length=54, primary_key=True, serialize=False, unique=True, verbose_name='Order ID')),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Preparing'), (3, 'Ready'), (4, 'Delivered'), (5, 'Cancelled')], default=0, max_length=20, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Amount')),
                ('order_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Order Date')),
                ('delivered_date', models.DateTimeField(blank=True, null=True, verbose_name='Delivered Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customeruser', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', accounts.fields.PrefixedIDField(editable=False, max_length=58, primary_key=True, serialize=False, unique=True, verbose_name='Order Item ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Price')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurant.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['id'], name='ord_id_index'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['id'], name='ord_itm_id_index'),
        ),
    ]
