# Generated by Django 5.2.2 on 2025-06-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurant', '0002_restaurantpackagedmaterial_package_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.restaurant', verbose_name='Restaurant'),
        ),
    ]
