# Generated by Django 5.2.2 on 2025-06-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Preparing'), (3, 'Ready'), (4, 'Delivered'), (5, 'Cancelled')], default=0, max_length=20, verbose_name='Status'),
        ),
    ]
