# Generated by Django 5.2.2 on 2025-06-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Preparing'), (3, 'Ready'), (4, 'Delivered'), (5, 'Cancelled')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount'),
        ),
    ]
