# Generated by Django 5.2.2 on 2025-06-14 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status_alter_order_total_amount'),
        ('restaurant', '0004_alter_restaurantpackagedmaterial_finished_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
